Repository MTrab/energidataservice, pull requests merged in 2023-01, with the labels that each got.

#166 Automatically pull tariff data
  .gitignore
  custom_components/energidataservice/__init__.py
  custom_components/energidataservice/config_flow.py
  custom_components/energidataservice/const.py
  custom_components/energidataservice/diagnostics.py
  custom_components/energidataservice/manifest.json
  custom_components/energidataservice/sensor.py
  custom_components/energidataservice/tariffs/__init__.py
  custom_components/energidataservice/tariffs/eloverblik/__init__.py
  custom_components/energidataservice/tariffs/eloverblik/regions.py
  custom_components/energidataservice/translations/da.json
  custom_components/energidataservice/translations/en.json
  custom_components/energidataservice/utils/configuration_schema.py
  requirements.txt
Labels: minor, enhancement

#167 Fix wrong translation
  custom_components/energidataservice/translations/da.json
Labels: patch, enhancement

#168 Add tariffs for use in templates
  custom_components/energidataservice/sensor.py
Labels: patch, enhancement

#169 Add fixed price connector
  custom_components/energidataservice/__init__.py
  custom_components/energidataservice/config_flow.py
  custom_components/energidataservice/connectors/__init__.py
  custom_components/energidataservice/connectors/energidataservice/__init__.py
  custom_components/energidataservice/connectors/fixedprice/__init__.py
  custom_components/energidataservice/connectors/fixedprice/regions.py
  custom_components/energidataservice/connectors/nordpool/__init__.py
  custom_components/energidataservice/const.py
  custom_components/energidataservice/sensor.py
  custom_components/energidataservice/translations/da.json
  custom_components/energidataservice/translations/en.json
  custom_components/energidataservice/utils/configuration_schema.py
Labels: major, enhancement

#170 Fixing bug in config_flow when updating configuration
  custom_components/energidataservice/config_flow.py
Labels: bug, patch

#171 Add Energi Data Service tariff connector and remove Eloverblik for faster and more reliable integration loads
  .github/scripts/update_chargeowners.py
  .github/workflows/release.yml
  custom_components/energidataservice/__init__.py
  custom_components/energidataservice/config_flow.py
  custom_components/energidataservice/const.py
  custom_components/energidataservice/diagnostics.py
  custom_components/energidataservice/sensor.py
  custom_components/energidataservice/tariffs/__init__.py
  custom_components/energidataservice/tariffs/eloverblik/__init__.py
  custom_components/energidataservice/tariffs/energidataservice/__init__.py
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
  custom_components/energidataservice/tariffs/energidataservice/regions.py
  custom_components/energidataservice/translations/da.json
  custom_components/energidataservice/translations/en.json
  custom_components/energidataservice/utils/configuration_schema.py
  custom_components/energidataservice/utils/tariffhandler.py
Labels: minor, enhancement

#172 Fix errors with default price for new fixed price connector
  custom_components/energidataservice/tariffs/__init__.py
  custom_components/energidataservice/tariffs/energidataservice/regions.py
  custom_components/energidataservice/utils/configuration_schema.py
Labels: bug, patch

#173 Fixing error using Carnot and tariff together
  .github/scripts/update_chargeowners.py
  custom_components/energidataservice/config_flow.py
  custom_components/energidataservice/manifest.json
  custom_components/energidataservice/utils/configuration_schema.py
Labels: bug, patch

#182 Validation of dataset fixed for operators with shourt lived validity
  custom_components/energidataservice/tariffs/energidataservice/__init__.py
Labels: bug, patch

#176 Filtering invalid charge owners on update
  .github/scripts/update_chargeowners.py
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: bug, patch

#198 Add tariffs to the attribute list
  custom_components/energidataservice/sensor.py
Labels: enhancement

#197 Fixing tariffs request and missing operators
  .github/workflows/release.yml
  custom_components/energidataservice/sensor.py
  custom_components/energidataservice/tariffs/energidataservice/__init__.py
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
  custom_components/energidataservice/utils/tariffhandler.py
Labels: bug, minor

#199 Add net operator to attribute
  custom_components/energidataservice/sensor.py
Labels: patch, enhancement

#200 Only show tariff attributes if auto tariffs was enabled
  custom_components/energidataservice/sensor.py
Labels: patch, enhancement

#202 README update
  README.md
Labels: documentation

#201 Add error-handling for invalid charge owner
  custom_components/energidataservice/tariffs/energidataservice/__init__.py
Labels: patch, enhancement

#206 Adding Zeanet to charge owners
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: patch, enhancement

#209 Adding Tarm Elvaerk Net to charge owners
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: patch, enhancement

#212 Added missing link to net operator lookup
  custom_components/energidataservice/translations/da.json
  custom_components/energidataservice/translations/en.json
Labels: bug, patch

#219 Add correct GLN number for Netselskabet Elværk
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: bug, patch

#222 Adding Ravdex to charge owners
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: patch, enhancement

#223 Adding correct GLN for Veksel charge owner
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: bug, patch

#224 Adding El-net Kongerslev to charge owners
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: patch, enhancement

#226 Only show available options for the region
  custom_components/energidataservice/config_flow.py
  custom_components/energidataservice/utils/configuration_schema.py
  custom_components/energidataservice/utils/forecasthandler.py
Labels: patch, enhancement

#236 Fixed missing currency indicator
  custom_components/energidataservice/__init__.py
  custom_components/energidataservice/sensor.py
Labels: bug, patch

#234 Fix check of availability of extras
  custom_components/energidataservice/config_flow.py
Labels: bug, patch

#235 README/documentation update
  README.md
  assets/Carnot Credentials.png
  assets/Detailed Setup.png
  assets/Extra Services.png
  assets/Reconfigure.png
  assets/Select Charge Owner.png
  assets/Select Country.png
Labels: documentation

#232 Adding NKE-Elnet to charge owners
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: patch, enhancement

#230 Adding L-Net to charge owners
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: patch, enhancement
