Repository MTrab/energidataservice, pull requests merged in 2023-07, with the labels that each got.

#323 Updated date range to not include ValidTo and pulled the check into new method
  custom_components/energidataservice/tariffs/energidataservice/__init__.py
Labels: bug, patch

#324 Fix issue #319 new prices does not show until reload or at midnight
  custom_components/energidataservice/__init__.py
Labels: bug, patch

#329 Adding chargeowner label to release-drafter
  .github/release-drafter.yml
Labels: skip-changelog

#328 Switching to correct ChargeCodeType for Nord Energi Net
  custom_components/energidataservice/tariffs/energidataservice/chargeowners.py
Labels: patch, chargeowner
