Repository MTrab/energidataservice, pull requests merged in 2024-09, with the labels that each got.

#583 Retry update when tariff endpoint returns a non 200 response
  custom_components/energidataservice/api.py
Labels: patch

#570 Revert "Do not verify API SSL"
  custom_components/energidataservice/api.py
Labels: patch

#591 Fix error when tariff API is not responding
  config/configuration.yaml
  custom_components/energidataservice/api.py
  custom_components/energidataservice/tariffs/energidataservice/__init__.py
Labels: bug, patch

#574 Remove unnecessary call to template.attach
  custom_components/energidataservice/sensor.py
Labels: patch

#592 Enable long term statistics
  custom_components/energidataservice/sensor.py
Labels: patch, enhancement
